import type { Metadata } from "next";
import "./globals.css";
import FlyonuiScript from "@/components/FlyonuiScript";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "full-stack js developer portfolio web application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-serif`}>
        <Header />
        {children}
        <Footer />
      </body>
      <FlyonuiScript />
    </html>
  );
}
